# Generated by Django 3.1.7 on 2021-04-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_site', '0003_auto_20210403_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
