# Generated by Django 3.1.7 on 2021-05-01 19:39

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('landing_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='first_name',
            field=models.CharField(default='Jonathan', max_length=30),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='last_name',
            field=models.CharField(default='Joestar', max_length=30),
        ),
    ]
