# Generated by Django 3.1.7 on 2021-05-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_site', '0002_auto_20210501_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
