# Generated by Django 3.1.7 on 2021-04-10 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(max_length=30)),
                ('account_type', models.CharField(choices=[('checkings', 'Checkings'), ('savings', 'Savings'), ('credit', 'Credit')], max_length=20)),
                ('account_number', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('origin', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of Transaction')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('debit', 'Debit'), ('credit', 'Credit'), ('transfer', 'Transfer')], max_length=20)),
                ('description', models.TextField()),
                ('label', models.CharField(max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.bankaccountsmodel')),
            ],
        ),
    ]
