# Generated by Django 3.1.7 on 2021-04-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20210410_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsmodel',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
