# Generated by Django 3.1.7 on 2021-05-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_contactdeliverymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDeliveryModel',
        ),
    ]
